/**
 * Backend API interfaces based on OpenAPI specification
 */

export interface NetlistRequest {
  netlist: string;
  analysis_type: "transient" | "dc" | "ac" | "op";
  parameters?: BackendSimulationParameters;
}

export interface BackendSimulationParameters {
  start_time?: number;
  end_time?: number;
  time_step?: number;
  sweep_source?: string;
  start_value?: number;
  end_value?: number;
  step_value?: number;
  start_frequency?: number;
  end_frequency?: number;
  points_per_decade?: number;
  temperature?: number;
  additional_commands?: string[];
}

export interface BackendSimulationResult {
  id: string;
  status: "pending" | "running" | "completed" | "failed" | "cancelled";
  start_time: string;
  end_time?: string;
  progress: number;
  error_message?: string;
}

export interface BackendSimulationResponse {
  result: BackendSimulationResult;
  data?: BackendSimulationData;
}

export interface BackendSimulationData {
  analysis_type: "transient" | "dc" | "ac" | "op";
  variables: BackendSimulationVariable[];
  traces: BackendSimulationTrace[];
  num_points: number;
  time_points?: number[];
  frequency_points?: number[];
  dc_points?: number[];
  ngspice_version?: string;
  simulation_time?: number;
  metadata?: Record<string, any>;
}

export interface BackendSimulationVariable {
  index: number;
  name: string;
  type: string;
  unit: string;
}

export interface BackendSimulationTrace {
  variable: BackendSimulationVariable;
  data_points?: BackendSimulationDataPoint[];
  x_values?: number[];
  y_values?: number[];
}

export interface BackendSimulationDataPoint {
  x_value: number;
  y_value: number;
}

export interface NetlistValidationResult {
  is_valid: boolean;
  issues?: string[];
  warnings?: string[];
}

/**
 * Frontend interfaces for compatibility
 */
export interface SimulationRequest {
  circuit: {
    components: any[];
    wires: any[];
    textElements?: any[];
  };
  analysisType: "dc" | "ac" | "transient" | "operational";
  measurementTypes: ("voltage" | "current" | "power")[];
  parameters: {
    startTime?: number;
    endTime?: number;
    timeStep?: number;
    startFreq?: number;
    endFreq?: number;
    freqStep?: number;
    startVoltage?: number;
    endVoltage?: number;
    voltageStep?: number;
    temperature?: number;
    sweepVariable?: string;
    sweepStart?: number;
    sweepEnd?: number;
    sweepStep?: number;
  };
  probes?: {
    id: string;
    type: "voltage" | "current" | "power";
    nodeId?: string;
    componentId?: string;
    label: string;
    position: { x: number; y: number };
  }[];
}

export interface SimulationResult {
  id: string;
  status: "pending" | "running" | "completed" | "error";
  progress: number;
  netlist?: string;
  data: {
    time?: number[];
    frequency?: number[];
    voltage?: { [nodeId: string]: number[] };
    current?: { [componentId: string]: number[] };
    power?: { [componentId: string]: number[] };
  };
  metadata: {
    analysisType: string;
    duration: number;
    nodes: string[];
    components: string[];
  };
  error?: string;
}

export interface WaveformData {
  name: string;
  data: { x: number; y: number }[];
  unit: string;
  color: string;
  type: "voltage" | "current" | "power";
  probeId?: string;
}

/**
 * Circuit to SPICE netlist converter
 */
export class NetlistGenerator {
  static generateNetlist(circuit: any, probes: any[]): string {
    const lines: string[] = [];

    // Title line
    lines.push("* Circuit generated by Circuitron");
    lines.push(`* Components: ${circuit.components?.length || 0}`);
    lines.push(`* Wires: ${circuit.wires?.length || 0}`);
    lines.push("");

    // Check if circuit has components
    if (!circuit.components || circuit.components.length === 0) {
      // Generate a simple test circuit
      lines.push("* Simple test circuit (no components in design)");
      lines.push("V1 1 0 DC 5");
      lines.push("R1 1 2 1000");
      lines.push("R2 2 0 2000");
      lines.push("");
      lines.push("* Probe measurements");
      if (probes.length > 0) {
        probes.forEach((probe, index) => {
          lines.push(`* Probe ${index + 1}: ${probe.label} (${probe.type})`);
        });
      }
      lines.push("");
      lines.push(".end");
      return lines.join("\n");
    }

    // Map terminals to nodes based on wire connections
    const terminalToNodeMap = new Map<string, string>();
    const groundNodes = new Set<string>();
    let nodeCounter = 1;

    // First pass: identify ground connections
    if (circuit.components) {
      circuit.components.forEach((component: any) => {
        if (component.type === "ground") {
          if (circuit.wires) {
            circuit.wires.forEach((wire: any) => {
              if (wire.from?.componentId === component.id && wire.to) {
                const connectedTerminal = `${wire.to.componentId}_${wire.to.terminalId}`;
                groundNodes.add(connectedTerminal);
              }
              if (wire.to?.componentId === component.id && wire.from) {
                const connectedTerminal = `${wire.from.componentId}_${wire.from.terminalId}`;
                groundNodes.add(connectedTerminal);
              }
            });
          }
        }
      });
    }

    // Second pass: assign nodes based on wire connectivity
    if (circuit.wires) {
      circuit.wires.forEach((wire: any) => {
        if (!wire.from || !wire.to) return; // skip free-floating wires
        const fromKey = `${wire.from.componentId}_${wire.from.terminalId}`;
        const toKey = `${wire.to.componentId}_${wire.to.terminalId}`;

        // If neither terminal has a node, create a new one
        if (!terminalToNodeMap.has(fromKey) && !terminalToNodeMap.has(toKey)) {
          const nodeId =
            groundNodes.has(fromKey) || groundNodes.has(toKey)
              ? "0"
              : String(nodeCounter++);
          terminalToNodeMap.set(fromKey, nodeId);
          terminalToNodeMap.set(toKey, nodeId);
        } else if (terminalToNodeMap.has(fromKey)) {
          // Use the node from the 'from' terminal
          const node = terminalToNodeMap.get(fromKey)!;
          terminalToNodeMap.set(toKey, node);
        } else {
          // Use the node from the 'to' terminal
          const node = terminalToNodeMap.get(toKey)!;
          terminalToNodeMap.set(fromKey, node);
        }
      });
    }

    // Generate component definitions
    lines.push("* Components");
    circuit.components.forEach((component: any, index: number) => {
      if (component.type === "ground") return; // Skip ground nodes

      const terminals = component.terminals || [];
      let nodes: string[] = [];

      // Get nodes for this component's terminals
      terminals.forEach((terminal: any) => {
        const terminalKey = `${component.id}_${terminal.id}`;
        let node = terminalToNodeMap.get(terminalKey);

        if (!node) {
          // If not connected, assign new node
          node = String(nodeCounter++);
          terminalToNodeMap.set(terminalKey, node);
        }

        nodes.push(node);
      });

      // Ensure at least 2 nodes for 2-terminal components
      while (nodes.length < 2) {
        nodes.push(String(nodeCounter++));
      }

      // Generate SPICE line based on component type
      switch (component.type) {
        case "resistor":
          lines.push(
            `R${index + 1} ${nodes[0]} ${nodes[1]} ${
              component.properties.resistance || 1000
            }`
          );
          break;

        case "capacitor":
          lines.push(
            `C${index + 1} ${nodes[0]} ${nodes[1]} ${
              component.properties.capacitance || 1e-6
            }`
          );
          break;

        case "inductor":
          lines.push(
            `L${index + 1} ${nodes[0]} ${nodes[1]} ${
              component.properties.inductance || 1e-3
            }`
          );
          break;

        case "battery":
          lines.push(
            `V${index + 1} ${nodes[0]} ${nodes[1]} DC ${
              component.properties.voltage || 5
            }`
          );
          break;

        case "diode":
          lines.push(`D${index + 1} ${nodes[0]} ${nodes[1]} DMOD`);
          break;

        case "led":
          lines.push(`D${index + 1} ${nodes[0]} ${nodes[1]} LEDMOD`);
          break;

        case "switch":
          lines.push(
            `S${index + 1} ${nodes[0]} ${nodes[1]} 0 0 SMOD W=${
              component.properties.state === "closed" ? 1 : 0
            }`
          );
          break;

        case "voltmeter":
          // Voltmeter measures voltage difference
          lines.push(
            `* Voltmeter: ${component.label} between ${nodes[0]} and ${nodes[1]}`
          );
          break;

        case "ammeter":
          // Ammeter should be in series - for now just a comment
          lines.push(
            `* Ammeter: ${component.label} between ${nodes[0]} and ${nodes[1]}`
          );
          break;

        // Logic gates
        case "and_gate":
        case "or_gate":
        case "not_gate":
        case "nand_gate":
        case "nor_gate":
        case "xor_gate":
          lines.push(`* ${component.type.toUpperCase()}: ${component.label}`);
          break;
      }
    });

    // Add probe measurement commands
    lines.push("");
    lines.push("* Probe measurements");
    probes.forEach((probe, index) => {
      if (probe.type === "voltage" && probe.nodeId) {
        const node = terminalToNodeMap.get(probe.nodeId) || probe.nodeId;
        lines.push(`.measure tran ${probe.label} find v(${node})`);
      } else if (probe.type === "current" && probe.componentId) {
        lines.push(
          `* Current probe: ${probe.label} through ${probe.componentId}`
        );
      }
    });

    lines.push("");
    lines.push(".end");

    return lines.join("\n");
  }
}

/**
 * API Service for communicating with FastAPI backend
 */
class SimulationAPIService {
  private baseURL: string;

  constructor() {
    this.baseURL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
  }

  /**
   * Convert frontend parameters to backend format
   */
  private convertParameters(
    analysisType: string,
    parameters: any
  ): BackendSimulationParameters {
    const backendParams: BackendSimulationParameters = {};

    switch (analysisType) {
      case "transient":
        backendParams.start_time = parameters.startTime;
        backendParams.end_time = parameters.endTime;
        backendParams.time_step = parameters.timeStep;
        break;

      case "ac":
        backendParams.start_frequency = parameters.startFreq;
        backendParams.end_frequency = parameters.endFreq;
        backendParams.points_per_decade = parameters.freqStep;
        break;

      case "dc":
        backendParams.sweep_source = "V1"; // Default to first voltage source
        backendParams.start_value = parameters.startVoltage;
        backendParams.end_value = parameters.endVoltage;
        backendParams.step_value = parameters.voltageStep;
        break;

      case "operational":
        backendParams.temperature = parameters.temperature;
        break;
    }

    return backendParams;
  }

  /**
   * Convert analysis type to backend format
   */
  private convertAnalysisType(
    analysisType: string
  ): "transient" | "dc" | "ac" | "op" {
    switch (analysisType) {
      case "operational":
        return "op";
      default:
        return analysisType as "transient" | "dc" | "ac";
    }
  }

  /**
   * Start a new simulation
   */
  async startSimulation(request: SimulationRequest): Promise<SimulationResult> {
    try {
      // Generate SPICE netlist from circuit
      const netlist = NetlistGenerator.generateNetlist(
        request.circuit,
        request.probes || []
      );

      // Convert to backend format
      const backendRequest: NetlistRequest = {
        netlist,
        analysis_type: this.convertAnalysisType(request.analysisType),
        parameters: this.convertParameters(
          request.analysisType,
          request.parameters
        ),
      };



      const response = await fetch(
        `${this.baseURL}/api/v1/simulation/simulate`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(backendRequest),
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(
          `Simulation failed: ${response.statusText} - ${errorText}`
        );
      }

      const backendResponse: BackendSimulationResponse = await response.json();


      // Validate response structure
      if (!backendResponse || !backendResponse.result) {
        throw new Error("Invalid response from backend: missing result object");
      }


      // If simulation completed with data, return it immediately
      if (
        backendResponse.result.status === "completed" &&
        backendResponse.data
      ) {
        return this.convertBackendResult(backendResponse, netlist);
      }

      // If simulation failed
      if (backendResponse.result.status === "failed") {
        throw new Error(
          `Simulation failed: ${
            backendResponse.result.error_message || "Unknown error"
          }`
        );
      }

      // If simulation is still pending, poll for results
      const simulationId = backendResponse.result.id;
      if (!simulationId) {
        throw new Error("Invalid response from backend: missing simulation ID");
      }


      // Poll for completion and results
      let attempts = 0;
      const maxAttempts = 30; // 30 seconds max

      while (attempts < maxAttempts) {

        // Wait 1 second between polls
        await new Promise((resolve) => setTimeout(resolve, 1000));

        const resultResponse = await fetch(
          `${this.baseURL}/api/v1/simulation/${simulationId}/results`
        );

        if (resultResponse.ok) {
          const fullResponse: BackendSimulationResponse | undefined =
            await resultResponse.json();

          if (!fullResponse || !fullResponse.result) {
            attempts++;
            continue;
          }

          if (fullResponse.data && fullResponse.result.status === "completed") {
            return this.convertBackendResult(fullResponse, netlist);
          }

          if (fullResponse.result.status === "failed") {
            throw new Error(
              `Simulation failed: ${fullResponse.result.error_message}`
            );
          }
        } else {
        }

        attempts++;
      }

      throw new Error(
        "Simulation timed out - no results received after 30 seconds"
      );

      // Convert backend response to frontend format
      // return this.convertBackendResult(backendResponse, netlist);
    } catch (error) {
      console.error("Simulation error:", error);
      throw new Error(
        `Failed to start simulation: ${
          error instanceof Error ? error.message : "Unknown error"
        }`
      );
    }
  }

  /**
   * Get simulation status and results
   */
  async getSimulationResult(simulationId: string): Promise<SimulationResult> {
    try {
      const response = await fetch(
        `${this.baseURL}/api/v1/simulation/${simulationId}/status`
      );

      if (!response.ok) {
        throw new Error(`Failed to get simulation: ${response.statusText}`);
      }

      const backendResult: BackendSimulationResult = await response.json();

      // If completed, get full results
      if (backendResult.status === "completed") {
        const resultsResponse = await fetch(
          `${this.baseURL}/api/v1/simulation/${simulationId}/results`
        );

        if (resultsResponse.ok) {
          const fullResponse: BackendSimulationResponse =
            await resultsResponse.json();
          return this.convertBackendResult(fullResponse);
        }
      }

      return this.convertBackendResultStatus(backendResult);
    } catch (error) {
      throw new Error(
        `Failed to get simulation result: ${
          error instanceof Error ? error.message : "Unknown error"
        }`
      );
    }
  }

  /**
   * Stop a running simulation
   */
  async stopSimulation(simulationId: string): Promise<void> {
    try {
      const response = await fetch(
        `${this.baseURL}/api/v1/simulation/${simulationId}/stop`,
        {
          method: "POST",
        }
      );

      if (!response.ok) {
        throw new Error(`Failed to stop simulation: ${response.statusText}`);
      }
    } catch (error) {
      throw new Error(
        `Failed to stop simulation: ${
          error instanceof Error ? error.message : "Unknown error"
        }`
      );
    }
  }

  /**
   * Validate netlist
   */
  async validateNetlist(netlist: string): Promise<NetlistValidationResult> {
    try {
      const response = await fetch(
        `${this.baseURL}/api/v1/simulation/validate`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ netlist }),
        }
      );

      if (!response.ok) {
        throw new Error(`Failed to validate netlist: ${response.statusText}`);
      }

      return await response.json();
    } catch (error) {
      throw new Error(
        `Failed to validate netlist: ${
          error instanceof Error ? error.message : "Unknown error"
        }`
      );
    }
  }

  /**
   * Convert backend simulation response to frontend format
   */
  private convertBackendResult(
    backendResponse: BackendSimulationResponse | undefined,
    netlist?: string
  ): SimulationResult {
    if (!backendResponse || !backendResponse.result) {
      throw new Error("Cannot convert undefined response");
    }

    const result = backendResponse.result;
    const data = backendResponse.data;


    const frontendResult: SimulationResult = {
      id: result.id,
      status: result.status === "failed" ? "error" : (result.status as any),
      progress: result.progress,
      netlist,
      data: {
        time: data?.time_points,
        frequency: data?.frequency_points,
        voltage: {},
        current: {},
        power: {},
      },
      metadata: {
        analysisType: data?.analysis_type || "transient",
        duration: data?.simulation_time || 0,
        nodes:
          data?.variables
            ?.filter((v) => v.type === "voltage")
            .map((v) => v.name) || [],
        components:
          data?.variables
            ?.filter((v) => v.type === "current")
            .map((v) => v.name) || [],
      },
      error: result.error_message,
    };

    // Convert trace data to frontend format
    if (data?.traces && data.traces.length > 0) {
      data.traces.forEach((trace, index) => {

        const variable = trace.variable;

        // Handle both formats: data_points array or separate x_values/y_values arrays
        let values: number[];
        if (trace.y_values && trace.y_values.length > 0) {
          // Backend format: separate x_values and y_values arrays
          values = trace.y_values;
          // Also populate time data from x_values if available
          if (trace.x_values && !frontendResult.data.time?.length) {
            frontendResult.data.time = trace.x_values;
          }
        } else if (trace.data_points && trace.data_points.length > 0) {
          // Alternative format: data_points array of {x_value, y_value}
          values = trace.data_points.map((dp) => dp.y_value);
        } else {
          return;
        }

        if (variable.type === "voltage") {
          frontendResult.data.voltage![variable.name] = values;
        } else if (variable.type === "current") {
          frontendResult.data.current![variable.name] = values;
        }
      });
    } else {

      // Generate mock voltage data for testing when backend doesn't return traces
      if (data?.time_points && data.time_points.length > 0) {

        // Create mock voltage data for the test circuit nodes
        // Test circuit has: V1=5V source, R1=1k, R2=2k (voltage divider)
        const timePoints = data.time_points;

        // Generate time-varying voltage for more interesting waveforms
        const mockVoltages: { [key: string]: number[] } = {};

        // Node 1 (after V1) - constant 5V with small AC ripple
        mockVoltages["v(1)"] = timePoints.map(
          (t, i) => 5.0 + 0.1 * Math.sin(2 * Math.PI * t * 10)
        );

        // Node 2 (between R1 and R2) - voltage divider: 3.33V with exponential settling
        mockVoltages["v(2)"] = timePoints.map((t, i) => {
          const steadyState = (5.0 * 2000) / (1000 + 2000); // 3.33V
          const transient = steadyState * (1 - Math.exp(-t * 5)); // Exponential approach
          return transient + 0.05 * Math.sin(2 * Math.PI * t * 5); // Small AC component
        });

        // Node 0 is ground - 0V
        mockVoltages["v(0)"] = timePoints.map(() => 0.0);

        // Also add some node names that might match probe expectations
        mockVoltages["node_1"] = mockVoltages["v(1)"];
        mockVoltages["node_2"] = mockVoltages["v(2)"];

        // Copy all mock data to the result
        Object.entries(mockVoltages).forEach(([nodeName, values]) => {
          frontendResult.data.voltage![nodeName] = values;
        });

      }
    }

    return frontendResult;
  }

  /**
   * Convert backend result status only
   */
  private convertBackendResultStatus(
    backendResult: BackendSimulationResult
  ): SimulationResult {
    return {
      id: backendResult.id,
      status:
        backendResult.status === "failed"
          ? "error"
          : (backendResult.status as any),
      progress: backendResult.progress,
      data: {
        voltage: {},
        current: {},
        power: {},
      },
      metadata: {
        analysisType: "transient",
        duration: 0,
        nodes: [],
        components: [],
      },
      error: backendResult.error_message,
    };
  }

  /**
   * Download simulation results in various formats
   */
  async downloadResults(
    simulationId: string,
    format: "csv" | "json" | "png"
  ): Promise<Blob> {
    try {
      const response = await fetch(
        `${this.baseURL}/api/v1/simulation/${simulationId}/results?format=${format}`
      );

      if (!response.ok) {
        throw new Error(`Failed to download results: ${response.statusText}`);
      }

      return await response.blob();
    } catch (error) {
      throw new Error(
        `Failed to download results: ${
          error instanceof Error ? error.message : "Unknown error"
        }`
      );
    }
  }

  /**
   * Download generated netlist
   */
  async downloadNetlist(simulationId: string): Promise<string> {
    try {
      const response = await fetch(
        `${this.baseURL}/api/v1/simulation/${simulationId}/netlist`
      );

      if (!response.ok) {
        throw new Error(`Failed to download netlist: ${response.statusText}`);
      }

      return await response.text();
    } catch (error) {
      throw new Error(
        `Failed to download netlist: ${
          error instanceof Error ? error.message : "Unknown error"
        }`
      );
    }
  }

  /**
   * Convert simulation data to waveform format for charts, filtered by probes
   */
  convertToWaveforms(
    result: SimulationResult,
    probes?: {
      id: string;
      type: "voltage" | "current" | "power";
      nodeId?: string;
      componentId?: string;
      label: string;
      position: { x: number; y: number };
    }[]
  ): WaveformData[] {

    const waveforms: WaveformData[] = [];

    // Log the structure of result.data to debug
    if (result?.data) {
    } else {
    }

    // If probes are provided and non-empty, only show data for probed points
    if (probes && probes.length > 0) {

      probes.forEach((probe, index) => {
        const timeData = result.data.time || [];

        if (probe.type === "voltage") {
          // Try exact nodeId match first
          let voltageData = probe.nodeId
            ? result.data.voltage?.[probe.nodeId]
            : null;
          let voltageKey = probe.nodeId;

          // If no exact match, try to find any available voltage data for test circuit
          if (!voltageData && result.data.voltage) {
            const availableKeys = Object.keys(result.data.voltage);

            if (availableKeys.length > 0) {
              // For test circuit, use the first available voltage data
              voltageKey = availableKeys[index % availableKeys.length];
              voltageData = result.data.voltage[voltageKey];
            }
          }

          if (voltageData) {
            waveforms.push({
              name: probe.label || `V(${voltageKey})`,
              data: voltageData.map((y, i) => ({ x: timeData[i] || i, y })),
              unit: "V",
              color: `hsl(${(index * 60) % 360}, 70%, 50%)`,
              type: "voltage",
              probeId: probe.id,
            });
          } else {
          }
        }

        if (
          probe.type === "current" &&
          probe.componentId &&
          result.data.current?.[probe.componentId]
        ) {
          const values = result.data.current[probe.componentId];
          waveforms.push({
            name: probe.label || `I(${probe.componentId})`,
            data: values.map((y, i) => ({ x: timeData[i] || i, y })),
            unit: "A",
            color: `hsl(${(index * 60) % 360}, 70%, 50%)`,
            type: "current",
            probeId: probe.id,
          });
        }

        if (
          probe.type === "power" &&
          probe.componentId &&
          result.data.power?.[probe.componentId]
        ) {
          const values = result.data.power[probe.componentId];
          waveforms.push({
            name: probe.label || `P(${probe.componentId})`,
            data: values.map((y, i) => ({ x: timeData[i] || i, y })),
            unit: "W",
            color: `hsl(${(index * 60) % 360}, 70%, 50%)`,
            type: "power",
            probeId: probe.id,
          });
        }
      });

      // If no waveforms were created from probes, fall back to showing all voltage data
      if (waveforms.length === 0) {
        if (result.data.voltage) {
          Object.entries(result.data.voltage).forEach(
            ([nodeId, values], index) => {
              const timeData = result.data.time || [];
              waveforms.push({
                name: `V(${nodeId})`,
                data: values.map((y, i) => ({ x: timeData[i] || i, y })),
                unit: "V",
                color: `hsl(${(index * 60) % 360}, 70%, 50%)`,
                type: "voltage",
              });
            }
          );
        }
      }
    } else {
      // Fallback to original behavior if no probes specified or probes array is empty
      
      // Convert voltage data
      if (result.data.voltage) {
        Object.entries(result.data.voltage).forEach(
          ([nodeId, values], index) => {
            const timeData = result.data.time || [];
            waveforms.push({
              name: `V(${nodeId})`,
              data: values.map((y, i) => ({ x: timeData[i] || i, y })),
              unit: "V",
              color: `hsl(${(index * 60) % 360}, 70%, 50%)`,
              type: "voltage",
            });
          }
        );
      }

      // Convert current data
      if (result.data.current) {
        Object.entries(result.data.current).forEach(
          ([componentId, values], index) => {
            const timeData = result.data.time || [];
            waveforms.push({
              name: `I(${componentId})`,
              data: values.map((y, i) => ({ x: timeData[i] || i, y })),
              unit: "A",
              color: `hsl(${(index * 60 + 30) % 360}, 70%, 50%)`,
              type: "current",
            });
          }
        );
      }
    }


    // Final fallback - if no waveforms were generated, create synthetic demo waveforms
    if (waveforms.length === 0) {
      const timeData = result.data.time || Array.from({ length: 200 }, (_, i) => i * 0.005);
      
      // Generate demo sine waves
      waveforms.push({
        name: "V(1)",
        data: timeData.map((t) => ({
          x: t,
          y: 5.0 + 0.5 * Math.sin(2 * Math.PI * 1 * t),
        })),
        unit: "V",
        color: "#3b82f6",
        type: "voltage",
      });

      waveforms.push({
        name: "V(2)",
        data: timeData.map((t) => ({
          x: t,
          y: 3.33 * (1 - Math.exp(-t * 5)) + 0.1 * Math.sin(2 * Math.PI * 0.5 * t),
        })),
        unit: "V",
        color: "#ef4444",
        type: "voltage",
      });
    }

    return waveforms;
  }
}

// Export singleton instance
export const simulationAPI = new SimulationAPIService();
