import { Circuit, CircuitComponent, Wire } from "@/types/circuit";

/**
 * Advanced Netlist Generator for SPICE simulation
 * Converts circuit drawing to valid SPICE netlist format
 */
export class AdvancedNetlistGenerator {
  private nodeMap: Map<string, string>;
  private nodeCounter: number;
  private lines: string[];

  constructor() {
    this.nodeMap = new Map();
    this.nodeCounter = 1;
    this.lines = [];
  }

  /**
   * Generate complete SPICE netlist from circuit
   */
  static generateNetlist(circuit: Circuit): string {
    const generator = new AdvancedNetlistGenerator();
    return generator.generate(circuit);
  }

  /**
   * Generate and return validation result
   */
  static generateWithValidation(circuit: Circuit): {
    netlist: string;
    errors: string[];
    warnings: string[];
  } {
    const generator = new AdvancedNetlistGenerator();
    const errors = generator.validateCircuit(circuit);
    const netlist = errors.length === 0 ? generator.generate(circuit) : "";

    return { netlist, errors, warnings: [] };
  }

  /**
   * Validate circuit before generation
   */
  private validateCircuit(circuit: Circuit): string[] {
    const errors: string[] = [];

    // Check if circuit has components
    if (!circuit.components || circuit.components.length === 0) {
      errors.push("Circuit has no components");
    }

    // Check for unconnected components
    const connectedComponents = new Set<string>();
    if (circuit.wires) {
      circuit.wires.forEach((wire) => {
        if (wire.from) connectedComponents.add(wire.from.componentId);
        if (wire.to) connectedComponents.add(wire.to.componentId);
      });
    }

    // Check for voltage sources
    const hasVoltageSource = circuit.components.some(
      (c) => c.type === "battery"
    );
    if (!hasVoltageSource && circuit.components.length > 0) {
      console.warn("Circuit has no voltage source - simulation may fail");
    }

    // Check for ground
    const hasGround = circuit.components.some((c) => c.type === "ground");
    if (!hasGround && circuit.components.length > 0) {
      console.warn("Circuit has no ground - this may cause simulation issues");
    }

    return errors;
  }

  /**
   * Main generation method
   */
  private generate(circuit: Circuit): string {
    this.lines = [];
    this.nodeMap.clear();
    this.nodeCounter = 1;

    // Title
    this.addLine("* Circuit: " + circuit.name);
    this.addLine("* Generated by Circuitron");
    this.addLine("");

    // Initialize ground node
    this.nodeMap.set("ground", "0");

    // Build node map from wires
    this.buildNodeMap(circuit);

    // Generate component definitions
    this.generateComponents(circuit);
    this.addLine("");

    // Generate .control section for transient analysis
    this.generateControlSection();

    this.addLine(".end");

    return this.lines.join("\n");
  }

  /**
   * Build mapping of component terminals to SPICE nodes
   */
  private buildNodeMap(circuit: Circuit): void {
    if (!circuit.wires) return;

    const componentNodeCounts = new Map<string, number>();

    // First pass: initialize counters
    circuit.components.forEach((comp) => {
      componentNodeCounts.set(comp.id, 0);
    });

    // Second pass: assign nodes based on wire connections
    circuit.wires.forEach((wire) => {
      if (!wire.from || !wire.to) return; // skip free-floating wires
      // Assign node to "from" terminal
      const fromKey = `${wire.from.componentId}_${wire.from.terminalId}`;
      if (!this.nodeMap.has(fromKey)) {
        this.nodeMap.set(fromKey, String(this.nodeCounter++));
      }

      // Assign same node to "to" terminal (they're connected)
      const toKey = `${wire.to.componentId}_${wire.to.terminalId}`;
      const connectedNode = this.nodeMap.get(fromKey)!;
      this.nodeMap.set(toKey, connectedNode);
    });

    // Assign default nodes to unconnected terminals
    circuit.components.forEach((comp) => {
      if (comp.terminals) {
        comp.terminals.forEach((terminal) => {
          const terminalKey = `${comp.id}_${terminal.id}`;
          if (!this.nodeMap.has(terminalKey)) {
            this.nodeMap.set(terminalKey, String(this.nodeCounter++));
          }
        });
      }
    });
  }

  /**
   * Generate SPICE component definitions
   */
  private generateComponents(circuit: Circuit): void {
    let resistorCount = 0;
    let capacitorCount = 0;
    let inductorCount = 0;
    let batteryCount = 0;
    let switchCount = 0;
    let diodeCount = 0;
    let transistorCount = 0;

    circuit.components.forEach((component) => {
      switch (component.type) {
        case "resistor":
          this.generateResistor(component, ++resistorCount);
          break;
        case "capacitor":
          this.generateCapacitor(component, ++capacitorCount);
          break;
        case "inductor":
          this.generateInductor(component, ++inductorCount);
          break;
        case "battery":
          this.generateVoltageSource(component, ++batteryCount);
          break;
        case "switch":
          this.generateSwitch(component, ++switchCount);
          break;
        case "diode":
          this.generateDiode(component, ++diodeCount);
          break;
        case "ground":
          // Ground is implicit - no netlist entry needed
          break;
        case "led":
          this.generateDiode(component, ++diodeCount, "LED");
          break;
        case "voltmeter":
          // Voltmeter is for measurement - handled in control section
          break;
        case "ammeter":
          // Ammeter requires zero voltage source
          this.generateVoltageSource(component, ++batteryCount, 0);
          break;
        case "npn_transistor":
        case "pnp_transistor":
        case "nmos_transistor":
        case "pmos_transistor":
          this.generateTransistor(component, ++transistorCount);
          break;
        default:
          console.warn(
            `Component type ${component.type} not yet supported in netlist generation`
          );
      }
    });
  }

  /**
   * Generate resistor netlist entry
   */
  private generateResistor(component: CircuitComponent, index: number): void {
    const terminals = component.terminals || [];
    if (terminals.length < 2) {
      console.error(`Resistor ${component.id} has less than 2 terminals`);
      return;
    }

    const node1 = this.getNodeForTerminal(component.id, terminals[0].id);
    const node2 = this.getNodeForTerminal(component.id, terminals[1].id);
    const resistance = (component.properties.resistance as number) || 1000;

    this.addLine(`R${index} ${node1} ${node2} ${resistance}`);
  }

  /**
   * Generate capacitor netlist entry
   */
  private generateCapacitor(component: CircuitComponent, index: number): void {
    const terminals = component.terminals || [];
    if (terminals.length < 2) return;

    const node1 = this.getNodeForTerminal(component.id, terminals[0].id);
    const node2 = this.getNodeForTerminal(component.id, terminals[1].id);
    const capacitance = (component.properties.capacitance as number) || 1e-6;

    this.addLine(`C${index} ${node1} ${node2} ${capacitance}`);
  }

  /**
   * Generate inductor netlist entry
   */
  private generateInductor(component: CircuitComponent, index: number): void {
    const terminals = component.terminals || [];
    if (terminals.length < 2) return;

    const node1 = this.getNodeForTerminal(component.id, terminals[0].id);
    const node2 = this.getNodeForTerminal(component.id, terminals[1].id);
    const inductance = (component.properties.inductance as number) || 1e-3;

    this.addLine(`L${index} ${node1} ${node2} ${inductance}`);
  }

  /**
   * Generate voltage source (battery)
   */
  private generateVoltageSource(
    component: CircuitComponent,
    index: number,
    forceValue?: number
  ): void {
    const terminals = component.terminals || [];
    if (terminals.length < 2) return;

    const node1 = this.getNodeForTerminal(component.id, terminals[0].id);
    const node2 = this.getNodeForTerminal(component.id, terminals[1].id);
    const voltage =
      forceValue !== undefined
        ? forceValue
        : (component.properties.voltage as number) || 5;

    // AC voltage source format: V<name> <node+> <node-> DC <value> [AC <amplitude> [<phase>]]
    this.addLine(`V${index} ${node1} ${node2} DC ${voltage}`);
  }

  /**
   * Generate switch netlist entry
   */
  private generateSwitch(component: CircuitComponent, index: number): void {
    const terminals = component.terminals || [];
    if (terminals.length < 2) return;

    const node1 = this.getNodeForTerminal(component.id, terminals[0].id);
    const node2 = this.getNodeForTerminal(component.id, terminals[1].id);

    // Simple switch model
    this.addLine(`S${index} ${node1} ${node2} ${node1} ${node2} MYSW`);
  }

  /**
   * Generate diode netlist entry
   */
  private generateDiode(
    component: CircuitComponent,
    index: number,
    type = "Diode"
  ): void {
    const terminals = component.terminals || [];
    if (terminals.length < 2) return;

    const node1 = this.getNodeForTerminal(component.id, terminals[0].id);
    const node2 = this.getNodeForTerminal(component.id, terminals[1].id);

    this.addLine(`D${index} ${node1} ${node2} DMOD`);
  }

  /**
   * Generate transistor netlist entry (BJT or MOSFET)
   */
  private generateTransistor(
    component: CircuitComponent,
    index: number
  ): void {
    const terminals = component.terminals || [];
    if (terminals.length < 3) {
      console.error(
        `Transistor ${component.id} has less than 3 terminals`
      );
      return;
    }

    const node0 = this.getNodeForTerminal(component.id, terminals[0].id);
    const node1 = this.getNodeForTerminal(component.id, terminals[1].id);
    const node2 = this.getNodeForTerminal(component.id, terminals[2].id);

    switch (component.type) {
      case "npn_transistor":
        // Q<name> <collector> <base> <emitter> <model>
        // terminals order: B(input), C(output), E(output)
        this.addLine(`Q${index} ${node1} ${node0} ${node2} NPN_MOD`);
        break;
      case "pnp_transistor":
        this.addLine(`Q${index} ${node1} ${node0} ${node2} PNP_MOD`);
        break;
      case "nmos_transistor":
        // M<name> <drain> <gate> <source> <bulk> <model>
        // terminals order: G(input), D(output), S(output)
        this.addLine(
          `M${index} ${node1} ${node0} ${node2} ${node2} NMOS_MOD`
        );
        break;
      case "pmos_transistor":
        this.addLine(
          `M${index} ${node1} ${node0} ${node2} ${node2} PMOS_MOD`
        );
        break;
    }
  }

  /**
   * Generate .control section for analysis
   */
  private generateControlSection(): void {
    this.addLine(".control");
    this.addLine("* Transient analysis: 0-1ms with 1us steps");
    this.addLine("tran 0 1m 0 1u");
    this.addLine("print all");
    this.addLine(".endc");
  }

  /**
   * Get node number for a specific terminal
   */
  private getNodeForTerminal(componentId: string, terminalId: string): string {
    const key = `${componentId}_${terminalId}`;
    return this.nodeMap.get(key) || "0";
  }

  /**
   * Add line to netlist
   */
  private addLine(text: string): void {
    this.lines.push(text);
  }
}

/**
 * SPICE netlist formatter and validator
 */
export class NetlistValidator {
  static validate(netlist: string): { isValid: boolean; errors: string[] } {
    const errors: string[] = [];

    if (!netlist || netlist.trim().length === 0) {
      errors.push("Netlist is empty");
      return { isValid: false, errors };
    }

    const lines = netlist.split("\n").filter((line) => line.trim());

    // Check for .end
    if (!lines.some((line) => line.toLowerCase().includes(".end"))) {
      errors.push("Netlist missing .end statement");
    }

    // Check for at least one component or voltage source
    const hasComponent = lines.some(
      (line) =>
        /^[rcldmviqxsw]\d+\s+/i.test(line.trim()) &&
        !line.trim().startsWith("*")
    );

    if (!hasComponent) {
      errors.push("Netlist has no components or sources");
    }

    return { isValid: errors.length === 0, errors };
  }

  /**
   * Format netlist for better readability
   */
  static format(netlist: string): string {
    return netlist
      .split("\n")
      .map((line) => {
        // Preserve comments
        if (line.trim().startsWith("*")) return line;
        if (line.trim().startsWith(".")) return line;

        // Format component lines
        const parts = line.split(/\s+/);
        if (parts.length > 0 && /^[rcldmviqxsw]\d+/i.test(parts[0])) {
          return line.padEnd(40) + " * Component line";
        }

        return line;
      })
      .join("\n");
  }
}

export const netlistGenerator = {
  generate: AdvancedNetlistGenerator.generateNetlist,
  generateWithValidation: AdvancedNetlistGenerator.generateWithValidation,
  validate: NetlistValidator.validate,
  format: NetlistValidator.format,
};
